# Generated by Django 4.2.7 on 2025-10-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('proposal', models.TextField(verbose_name='Предложение по стажировке')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена'), ('invited', 'Приглашены'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.company', verbose_name='Компания')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.internship', verbose_name='Стажировка')),
            ],
            options={
                'verbose_name': 'Отклик на стажировку',
                'verbose_name_plural': 'Отклики на стажировки',
                'ordering': ['-applied_at'],
            },
        ),
    ]
