# Generated by Django 4.2.7 on 2025-10-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_internshipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена'), ('invited', 'Приглашен'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.applicant', verbose_name='Соискатель')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.internship', verbose_name='Стажировка')),
            ],
            options={
                'verbose_name': 'Отклик на стажировку',
                'verbose_name_plural': 'Отклики на стажировки',
                'ordering': ['-applied_at'],
            },
        ),
    ]
