# Generated by Django 4.2.7 on 2025-10-17 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career_app', '0005_alter_category_options_category_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.CreateModel(
            name='RoleApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('hr', 'HR компании'), ('university', 'Представитель вуза')], max_length=20, verbose_name='Запрашиваемая роль')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Название компании')),
                ('institution_name', models.CharField(blank=True, max_length=200, verbose_name='Название учебного заведения')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на подтверждение роли',
                'verbose_name_plural': 'Запросы на подтверждение роли',
            },
        ),
    ]
