# Generated by Django 4.2.7 on 2025-10-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career_app', '0007_chatthread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealVacancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название профиля')),
                ('ideal_position', models.CharField(max_length=200, verbose_name='Идеальная должность')),
                ('desired_skills', models.TextField(verbose_name='Желаемые навыки')),
                ('experience_level', models.CharField(max_length=100, verbose_name='Уровень опыта')),
                ('desired_salary', models.CharField(blank=True, max_length=100, verbose_name='Желаемая зарплата')),
                ('location_preferences', models.CharField(blank=True, max_length=200, verbose_name='Предпочтения по локации')),
                ('min_match_percentage', models.IntegerField(default=70, verbose_name='Минимальный % совпадения')),
                ('max_vacancies', models.IntegerField(default=10, verbose_name='Максимум вакансий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.applicant', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Идеальный профиль вакансии',
                'verbose_name_plural': 'Идеальные профили вакансий',
            },
        ),
        migrations.CreateModel(
            name='IdealCandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название профиля')),
                ('ideal_resume', models.TextField(verbose_name='Идеальное резюме')),
                ('required_skills', models.TextField(verbose_name='Требуемые навыки')),
                ('experience_level', models.CharField(max_length=100, verbose_name='Уровень опыта')),
                ('education_requirements', models.TextField(blank=True, verbose_name='Требования к образованию')),
                ('min_match_percentage', models.IntegerField(default=70, verbose_name='Минимальный % совпадения')),
                ('max_candidates', models.IntegerField(default=10, verbose_name='Максимум кандидатов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='HR')),
            ],
            options={
                'verbose_name': 'Идеальный профиль кандидата',
                'verbose_name_plural': 'Идеальные профили кандидатов',
            },
        ),
        migrations.CreateModel(
            name='AISearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.IntegerField(verbose_name='Процент совпадения')),
                ('match_details', models.JSONField(default=dict, verbose_name='Детали совпадения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('offer_sent', 'Офер отправлен'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ideal_candidate_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_app.idealcandidateprofile')),
                ('ideal_vacancy_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_app.idealvacancyprofile')),
                ('matched_applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_app.applicant')),
                ('matched_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_app.vacancy')),
            ],
            options={
                'verbose_name': 'Результат ИИ-поиска',
                'verbose_name_plural': 'Результаты ИИ-поиска',
            },
        ),
    ]
