# Generated by Django 4.2.7 on 2025-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0008_idealvacancyprofile_idealcandidateprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Резюме опубликовано'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
    ]
