# Generated by Django 4.2.7 on 2025-10-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0009_applicant_about_applicant_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='employment_types',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_vacancy_profiles', to='career_app.category', verbose_name='Основная категория'),
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_vacancy_profiles', to='career_app.category', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='График работы'),
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег навыка',
                'verbose_name_plural': 'Теги навыков',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_app.educationlevel', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='selected_skill_tags',
            field=models.ManyToManyField(blank=True, to='career_app.skilltag', verbose_name='Выбранные теги навыков'),
        ),
    ]
