# Generated by Django 4.2.7 on 2025-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0010_educationlevel_idealvacancyprofile_employment_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(default='website', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('remote', 'Удаленная работа')], default='full', max_length=50, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата (число)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
