# Generated by Django 4.2.7 on 2025-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0011_application_ip_address_application_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('secondary_professional', 'Среднее профессиональное'), ('bachelor', 'Высшее (Бакалавр)'), ('master', 'Высшее (Магистр)'), ('phd', 'Высшее (Аспирант, PhD)')], max_length=50, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('no_experience', 'Нет опыта'), ('intern', 'Стажер'), ('junior', 'Junior (Начинающий)'), ('middle', 'Middle (Опытный)'), ('senior', 'Senior (Старший)'), ('lead', 'Lead (Руководитель)')], max_length=50, verbose_name='Уровень опыта'),
        ),
    ]
