# Generated by Django 4.2.7 on 2025-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0012_applicant_education_level_applicant_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealvacancyprofile',
            name='employment_types',
        ),
        migrations.RemoveField(
            model_name='idealvacancyprofile',
            name='ideal_position',
        ),
        migrations.RemoveField(
            model_name='idealvacancyprofile',
            name='work_schedule',
        ),
        migrations.AddField(
            model_name='idealvacancyprofile',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=500, verbose_name='Стек технологий'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('secondary_professional', 'Среднее профессиональное'), ('high', 'Высшее образование')], max_length=50, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='idealvacancyprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('secondary_professional', 'Среднее профессиональное'), ('high', 'Высшее образование')], default='high', max_length=50, verbose_name='Уровень образования'),
            preserve_default=False,
        ),
    ]
