# Generated by Django 4.2.7 on 2025-10-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0013_remove_idealvacancyprofile_employment_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealvacancyprofile',
            name='desired_skills',
            field=models.TextField(blank=True, verbose_name='Желаемые навыки'),
        ),
        migrations.AlterField(
            model_name='idealvacancyprofile',
            name='education_level',
            field=models.CharField(choices=[('secondary', 'Среднее'), ('secondary_professional', 'Среднее профессиональное'), ('high', 'Высшее образование')], default='high', max_length=50, verbose_name='Уровень образования'),
        ),
    ]
