# Generated by Django 4.2.7 on 2025-11-19 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название таймлайна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Таймлайн',
                'verbose_name_plural': 'Таймлайны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('era', models.CharField(choices=[('ancient', 'Древняя математика'), ('medieval', 'Средневековая математика'), ('renaissance', 'Эпоха Возрождения'), ('modern', 'Современная математика'), ('contemporary', 'Современность')], max_length=20, verbose_name='Эпоха')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline_constructor_app.timeline', verbose_name='Таймлайн')),
            ],
            options={
                'verbose_name': 'Событие таймлайна',
                'verbose_name_plural': 'События таймлайна',
                'ordering': ['year', 'order'],
            },
        ),
    ]
