# Generated by Django 4.2.7 on 2026-02-06 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('color_scheme', models.CharField(choices=[('green', 'Зеленая'), ('blue', 'Синяя'), ('purple', 'Фиолетовая'), ('orange', 'Оранжевая'), ('red', 'Красная'), ('teal', 'Бирюзовая')], default='green', max_length=20)),
                ('layout', models.CharField(choices=[('vertical', 'Вертикальный'), ('horizontal', 'Горизонтальный'), ('centered', 'Центрированный')], default='vertical', max_length=20)),
                ('show_dates', models.BooleanField(default=True)),
                ('show_images', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('board_x', models.FloatField(default=0, verbose_name='Позиция X на доске')),
                ('board_y', models.FloatField(default=0, verbose_name='Позиция Y на доске')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='timeline_constructor_app.timeline', verbose_name='Родительский таймлайн')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='timeline_constructor_app.timeline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(-3000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('era', models.CharField(choices=[('ancient', '🏛️ Древняя математика (до 500 г.)'), ('medieval', '⛪ Средневековая математика (500-1500)'), ('renaissance', '🎨 Эпоха Возрождения (1500-1700)'), ('enlightenment', '💡 Эпоха Просвещения (1700-1800)'), ('modern', '🔬 Современная математика (1800-1950)'), ('contemporary', '💻 Современность (1950-настоящее время)')], max_length=20)),
                ('event_type', models.CharField(choices=[('discovery', '🔍 Открытие'), ('invention', '⚡ Изобретение'), ('publication', '📚 Публикация'), ('theory', '🧠 Теория'), ('method', '🛠️ Метод'), ('award', '🏆 Награда'), ('birth', '👶 Рождение'), ('death', '⚰️ Смерть'), ('event', '📅 Событие')], default='event', max_length=20)),
                ('importance', models.IntegerField(choices=[(1, '⭐ Низкая'), (2, '⭐⭐ Средняя'), (3, '⭐⭐⭐ Высокая')], default=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline_images/')),
                ('source_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('board_x', models.FloatField(default=0, verbose_name='Позиция X на доске')),
                ('board_y', models.FloatField(default=0, verbose_name='Позиция Y на доске')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline_constructor_app.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='timeline_constructor_app.timeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.IntegerField(default=280)),
                ('height', models.IntegerField(default=180)),
                ('color', models.CharField(default='#10b981', max_length=20)),
                ('z_index', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_board_timelines', to=settings.AUTH_USER_MODEL)),
                ('original_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_board_versions', to='timeline_constructor_app.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='BoardNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('x', models.FloatField(default=100, verbose_name='Позиция X')),
                ('y', models.FloatField(default=100, verbose_name='Позиция Y')),
                ('color', models.CharField(default='#10b981', max_length=20, verbose_name='Цвет заголовка')),
                ('bg_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет фона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Узел доски',
                'verbose_name_plural': 'Узлы доски',
            },
        ),
        migrations.CreateModel(
            name='TimelineLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='timeline_constructor_app.timeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('timeline', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='timeline_constructor_app.timeline')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='timeline_constructor_app.timeline')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
