# Generated by Django 4.2.7 on 2025-11-19 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline_constructor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='color_scheme',
            field=models.CharField(choices=[('green', 'Зеленая'), ('blue', 'Синяя'), ('purple', 'Фиолетовая'), ('orange', 'Оранжевая')], default='green', max_length=20, verbose_name='Цветовая схема'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('discovery', 'Открытие'), ('invention', 'Изобретение'), ('publication', 'Публикация'), ('birth', 'Рождение'), ('death', 'Смерть'), ('event', 'Событие')], default='event', max_length=20, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], default=1, verbose_name='Важность'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.CreateModel(
            name='TimelineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='timeline_constructor_app.timeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='timeline_constructor_app.timeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('timeline', 'user')},
            },
        ),
    ]
