# Generated by Django 4.2.7 on 2026-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_constructor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='border_color',
            field=models.CharField(default='#10b981', max_length=20, verbose_name='Цвет рамки'),
        ),
    ]
