# Generated by Django 4.2.7 on 2025-11-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_constructor_app', '0002_timeline_color_scheme_timelineevent_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinecomment',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='timelinecomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year', 'created_at'], 'verbose_name': 'Событие таймлайна', 'verbose_name_plural': 'События таймлайна'},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='color_scheme',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='source_link',
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('discovery', 'Открытие'), ('invention', 'Изобретение'), ('publication', 'Публикация'), ('event', 'Событие')], default='event', max_length=20, verbose_name='Тип события'),
        ),
        migrations.DeleteModel(
            name='TimelineCollaborator',
        ),
        migrations.DeleteModel(
            name='TimelineComment',
        ),
    ]
