# Generated by Django 4.2.7 on 2026-02-06 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline_constructor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('x', models.FloatField(default=100, verbose_name='Позиция X')),
                ('y', models.FloatField(default=100, verbose_name='Позиция Y')),
                ('width', models.IntegerField(default=280, verbose_name='Ширина')),
                ('height', models.IntegerField(default=180, verbose_name='Высота')),
                ('color', models.CharField(default='#10b981', max_length=20, verbose_name='Цвет')),
                ('border_color', models.CharField(default='#10b981', max_length=20, verbose_name='Цвет рамки')),
                ('background_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет фона')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Заблокировано')),
                ('is_collapsed', models.BooleanField(default=False, verbose_name='Свернуто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('original_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_versions', to='timeline_constructor_app.timeline', verbose_name='Исходный таймлайн')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Таймлайн на доске',
                'verbose_name_plural': 'Таймлайны на доске',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_grid', models.BooleanField(default=True, verbose_name='Показывать сетку')),
                ('grid_size', models.IntegerField(default=50, verbose_name='Размер сетки')),
                ('grid_color', models.CharField(default='rgba(0,0,0,0.05)', max_length=20, verbose_name='Цвет сетки')),
                ('snap_to_grid', models.BooleanField(default=True, verbose_name='Привязка к сетке')),
                ('auto_arrange', models.BooleanField(default=False, verbose_name='Авторасположение')),
                ('board_background', models.CharField(default='#f8fafc', max_length=20, verbose_name='Фон доски')),
                ('last_view_x', models.FloatField(default=0, verbose_name='Последняя позиция X')),
                ('last_view_y', models.FloatField(default=0, verbose_name='Последняя позиция Y')),
                ('last_zoom', models.FloatField(default=1, verbose_name='Последний масштаб')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки доски',
                'verbose_name_plural': 'Настройки досок',
            },
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Метка')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Цвет линии')),
                ('line_style', models.CharField(choices=[('solid', 'Сплошная'), ('dashed', 'Пунктир'), ('dotted', 'Точки')], default='solid', max_length=20, verbose_name='Стиль линии')),
                ('arrow_type', models.CharField(choices=[('none', 'Без стрелки'), ('arrow', 'Стрелка'), ('circle', 'Круг')], default='arrow', max_length=20, verbose_name='Тип стрелки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='board.boardtimeline', verbose_name='Источник')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='board.boardtimeline', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Соединение на доске',
                'verbose_name_plural': 'Соединения на доске',
                'ordering': ['-created_at'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
